apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    zone: prod
    version: v1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node
            operator: In
            values:
            - arm
  containers:
  - name: hello-ctr
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: volv
      mountPath: /data
    resources:
      limits:
        memory: 256Mi
        cpu: 0.5
  volumes:
  - name: volv
    hostPath:
      path: /var/lib/darklab/darkbot-staging
      type: DirectoryOrCreate
