variables:
  IMAGE_PIPELINE_RUNNER: darkwind8/pipeline_images:kubectl-v1.23_v1
  DOCKER_HOST: tcp://dind-service:2375

stages:
  - test

.env_scrappy_staging: &env_scrappy_staging
  - echo "$env_scrappy_staging" > .env.scrappy

unit-testing-configurator:
  image: ${IMAGE_PIPELINE_RUNNER}
  stage: test
  before_script:
    - *env_scrappy_staging
  script:
    - python3 make.py configurator test

unit-testing:
  image: ${IMAGE_PIPELINE_RUNNER}
  stage: test
  before_script:
    - *env_scrappy_staging
  script:
    - python3 make.py scrappy test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

linting:
  image: ${IMAGE_PIPELINE_RUNNER}
  stage: test
  before_script:
    - *env_scrappy_staging
  script:
    - python3 make.py scrappy lint

migrate-scrappy:
  image: ${IMAGE_PIPELINE_RUNNER}
  stage: test
  before_script:
    - *env_scrappy_staging
  script:
    - python3 make.py scrappy migrate
