variables:
  IMAGE_PIPELINE_RUNNER: darkwind8/pipeline_images:kubectl-v1.23_v1
  DOCKER_HOST: tcp://dind-service:2375

stages:
  - test

unit-testing:
  image: ${IMAGE_PIPELINE_RUNNER}
  stage: test
  script:
    - python3 make.py scrappy test

linting:
  image: ${IMAGE_PIPELINE_RUNNER}
  stage: test
  script:
    - python3 make.py scrappy lint
