version: '3.8'
services:
  viewer_base:
    &viewer_base
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: dev
        SERVICE: viewer
    logging:
      driver: "json-file"
      options:
        max-buffer-size: "4m"
        mode: "non-blocking"
    environment:
      VIEWER_DISCORD_TOKEN: "${VIEWER_DISCORD_TOKEN:-example}"