version: '3.8'
services:
  listener_base:
    &listener_base
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: dev
        SERVICE: listener
    environment:
      LISTENER_DISCORD_TOKEN: "${LISTENER_DISCORD_TOKEN:-example}"