version: "3.3"
services:
    web:
        build:
            context: .
            dockerfile: dockerfile
        env_file: 
            - .env.prod
        volumes:
            - ./data:/data
        restart: always
