version: '3.8'
services:
  db:
    image: postgres:13
    expose:
      - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: default
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
  redis:
    image: redis
    expose:
      - "6379"
  service_base:
    &service_base
    build: 
      context: src
      dockerfile: scrappy/Dockerfile
    depends_on:
      - "db"
      - "redis"
    links:
      - db
      - redis
    volumes:
      - "./src:/code"
    command: python3 scripts_scrappy.py migrate_all
    environment:
      SCRAPPY_DATABASE_USERNAME: "postgres"
      SCRAPPY_DATABASE_PASSWORD: "postgres"
      SCRAPPY_DATABASE_HOST: "db"
    env_file:
      - .env.scrappy
  scrappy_web:
    <<: *service_base
    command: uvicorn scrappy.core.main:app --host 0.0.0.0
    ports:
      - "8000:8000"
  scrappy_geat:
    <<: *service_base
    command: celery -A scrappy.core.celery beat
  scrappy_worker:
    <<: *service_base
    command: celery -A scrappy.core.celery worker
  scrappy_flower:
    <<: *service_base
    command: celery -A scrappy.core.celery flower
    ports:
      - "5555:5555"