version: '3.8'
services:
  db:
    image: postgres:13
    expose:
      - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: default
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis
    expose:
      - "6379"
  service_base:
    &service_base
    build: 
      context: src
      dockerfile: scrappy/Dockerfile
    depends_on:
      - "db"
      - "redis"
    links:
      - db
      - redis
    command: python3 scripts_scrappy.py migrate_all
    environment:
      SCRAPPY_DATABASE_USERNAME: "postgres"
      SCRAPPY_DATABASE_PASSWORD: "postgres"
      SCRAPPY_DATABASE_HOST: "db"
      SCRAPPY_PLAYER_URL: "${SCRAPPY_PLAYER_URL:-example}"  
      SCRAPPY_BASE_URL: "${SCRAPPY_BASE_URL:-example}"
      SCRAPPY_FORUM_USERNAME: "${SCRAPPY_FORUM_USERNAME:-example}"
      SCRAPPY_FORUM_PASSWORD: "${SCRAPPY_FORUM_PASSWORD:-example}"
  service_web:
    <<: *service_base
    command: uvicorn scrappy.core.main:app --host 0.0.0.0
    ports:
      - "8000:8000"
  service_beat:
    <<: *service_base
    command: celery -A scrappy.core.celery beat
  service_worker:
    <<: *service_base
    command: celery -A scrappy.core.celery worker
  service_flower:
    <<: *service_base
    command: celery -A scrappy.core.celery flower
    ports:
      - "5555:5555"
  service_shell:
    <<: *service_base
    command: /bin/bash
    volumes:
      - "./src:/code"