version: '3.8'
services:
  listener_base:
    &listener_base
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: dev
        SERVICE: listener
      target: final-listener
    logging:
      driver: "json-file"
      options:
        max-buffer-size: "4m"
        mode: "non-blocking"
    environment:
      LISTENER_DISCORD_TOKEN: "${LISTENER_DISCORD_TOKEN:-example}"
    command: python3 -m listener