version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: default
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
  redis:
    image: redis
    ports:
      - "6379:6379"
  scrappy_base:
    &scrappy_base
    build: 
      context: src
      dockerfile: scrappy/Dockerfile
    depends_on:
      - "db"
      - "pgadmin"
      - "redis"
    links:
      - db
      - pgadmin
      - redis
    volumes:
      - "./src:/code"
    command: tail -F /dev/null
    environment:
      SCRAPPY_DATABASE_USERNAME: "postgres"
      SCRAPPY_DATABASE_PASSWORD: "postgres"
      SCRAPPY_DATABASE_HOST: "db"
    env_file:
      - .env.scrappy
  scrappy_web:
    <<: *scrappy_base
    command: uvicorn scrappy.core.main:app
  scrappy_geat:
    <<: *scrappy_base
    command: celery -A scrappy.core.celery beat
  scrappy_worker:
    <<: *scrappy_base
    command: celery -A scrappy.core.celery worker
  scrappy_flower:
    <<: *scrappy_base
    command: celery -A scrappy.core.celery flower
    ports:
      - "5555:5555"