version: '3'

services:
  app:
    build: .
    volumes:
      - "./data:/code/data"
      - "./app:/code/app"
    environment:
      DISCORDER_BOT_TOKEN: "${DISCORDER_BOT_TOKEN}"
      DARKBOT_LOG_LEVEL: "${DARKBOT_LOG_LEVEL}"
      CONFIGURATOR_DBNAME: "${CONFIGURATOR_DBNAME}"
