version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: default
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
  broker:
    image: rabbitmq
    ports:
      - "5672:5672"
  scrappy_base:
    &scrappy_base
    build: src/scrappy
    depends_on:
      - "db"
      - "broker"
      - "pgadmin"
    links:
      - db
      - broker
      - pgadmin
    volumes:
      - "./src/scrappy:/code"
  scrappy_web:
    <<: *scrappy_base
    command: python3 manage.py --action=run_web