version: '3.8'
services:
  discorder_base:
    extends:
      file: docker-compose.discorder.yml
      service: discorder_base
    depends_on:
      - discorder_integration
    environment:
      DISCORDER_API_URL: "http://discorder_integration:8000"
    command: sh -c './utils/scripts/wait_for_it.sh discorder_integration:8000 -t 20 && coverage run -m pytest -s -m "integration or not integration" && coverage report'
  discorder_integration:
    extends:
      file: docker-compose.discorder.yml
      service: discorder_base
    command: python3 -m discorder
    expose:
      - "8000"
    