site_name: Darkbot
site_description: discord bot for Freelancer Discovery
docs_dir: docs
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - sql
        - python

markdown_extensions:
    - def_list
    - pymdownx.tasklist
    - pymdownx.snippets
    - toc:
          permalink: "#"
          baselevel: 2
