site_name: Autogit article
site_description: about conventional commits and semantic versioning
docs_dir: docs
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - sql
        - python

markdown_extensions:
    - def_list
    - pymdownx.tasklist
    - pymdownx.snippets
    - toc:
          permalink: "#"
          baselevel: 2
