version: "3"
tasks:
  build-version:
    cmds:
      - autogit version > settings/version.txt || echo 'not installed autogit' > settings/version.txt

  build:
    cmds:
      - GOOS=linux GOARCH=amd64 go build -v -o main main.go

  test:
    cmds:
      - go test ./... {{.CLI_ARGS}}
    env:
      AUTOGIT_PROJECT_FOLDER:
        sh: echo "$(pwd)"

  doc-web:
    cmds:
      - godoc -http=:6060
