version: "3"
tasks:
  build-version:
    cmds:
      - autogit version > app/settings/version.txt || echo 'not installed autogit' > settings/version.txt

  build:
    cmds:
      - GOOS=linux GOARCH=amd64 go build -v -o main main.go

  test:
    cmds:
      # - go clean -cache ./...
      # - go clean -testcache ./...
      # -count=1
      - go test ./... -coverprofile=cover.out {{.CLI_ARGS}}
    env:
      AUTOGIT_PROJECT_FOLDER:
        sh: echo "$(pwd)"

  test:cover:
    cmds:
      - go tool cover -html=cover.out

  test:cover:total:
    cmds:
      - task: test
      - go tool cover -func cover.out


  doc-web:
    cmds:
      - godoc -http=:6060

  docker:build:
    cmds:
      - docker build --tag darkwind8/darkbot:v0.3.11-a.2 .

  docker:push:
    cmds:
      - docker push darkwind8/darkbot:v0.3.11-a.2

  docker:run:
    cmds:
      - docker run -it darkwind8/darkbot:v0.3.11-a.2

  docker:buildpush:
    cmds:
      - task: docker:build
      - task: docker:push

  shell:staging:
    cmds:
      - ssh -i ~/.ssh/id_rsa.darklab root@5.161.80.45

  mkdocs:dev:
    cmds:
      - poetry run -- mkdocs serve

  backup: # /var/lib/darklab/prod/darkbot
    cmds: # ssh -i ~/.ssh/id_rsa.darklab root@5.161.179.34
      - echo "TODO write command for backup"

  profile:run:
    cmds:
      - go run . run

  profile:render:
    cmds:
      - curl http://localhost:8080/debug/pprof/heap > heap.{{.DATE}}.pprof
      - go tool pprof --pdf ~/repos/pet_projects/darklab_darkbot/main heap.{{.DATE}}.pprof > file_{{.DATE}}.pdf
      - rm heap.{{.DATE}}.pprof
    vars:
      DATE:
        sh: date +%s

  profile:render2:
    cmds:
      - curl http://localhost:8080/debug/pprof/heap > heap.{{.DATE}}.pprof
      - go tool pprof --base heap.1675610376.pprof --pdf ~/repos/pet_projects/darklab_darkbot/main heap.{{.DATE}}.pprof > file_diff_{{.DATE}}.pdf
      - rm heap.{{.DATE}}.pprof
    vars:
      DATE:
        sh: date +%s

  profile:render3:
    cmds:
      - task: profile:render
      - task: profile:render2
