version: "3"
tasks:
  build-version:
    cmds:
      - autogit version > settings/version.txt || echo 'not installed autogit' > settings/version.txt

  build:
    cmds:
      - GOOS=linux GOARCH=amd64 go build -v -o main main.go

  test:
    cmds:
      - go test ./... {{.CLI_ARGS}}
    env:
      AUTOGIT_PROJECT_FOLDER:
        sh: echo "$(pwd)"

  doc-web:
    cmds:
      - godoc -http=:6060

  docker:build:
    cmds:
      - docker build --tag darkwind8/darkbot:v0.1.1 .

  docker:push:
    cmds:
      - docker push darkwind8/darkbot:v0.1.1

  mkdocs:init:
    cmds:
      - poetry install

  mkdocs:dev:
    cmds:
      - poetry run -- mkdocs serve

  backup: # /var/lib/darklab/prod/darkbot
    cmds: # ssh -i ~/.ssh/id_rsa.darklab root@5.161.179.34
      - echo "TODO write command for backup"
