variables:
  IMAGE_PIPELINE_RUNNER: darkwind8/pipeline_images:kubectl-v1.23_v1
  DOCKER_HOST: tcp://dind-service:2375

stages:
  - test

.env_scrappy_staging: &env_scrappy_staging
  - echo "$env_scrappy_staging" > .env.staging

unit-configurator:
  image: ${IMAGE_PIPELINE_RUNNER}
  stage: test
  before_script:
    - *env_scrappy_staging
  script:
    - python3 make.py configurator test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

unit-scrappy:
  image: ${IMAGE_PIPELINE_RUNNER}
  stage: test
  before_script:
    - *env_scrappy_staging
  script:
    - python3 make.py scrappy test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

discorder-scrappy:
  image: ${IMAGE_PIPELINE_RUNNER}
  stage: test
  before_script:
    - *env_scrappy_staging
  script:
    - python3 make.py discorder test
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

  # TODO add syntax for it being grabbable?
  # artifacts:
  #   reports:
  #     coverage_report:
  #       coverage_format: cobertura
  #       path: coverage.xml

lint-scrappy:
  image: ${IMAGE_PIPELINE_RUNNER}
  stage: test
  before_script:
    - *env_scrappy_staging
  script:
    - python3 make.py scrappy lint

lint-configurator:
  image: ${IMAGE_PIPELINE_RUNNER}
  stage: test
  before_script:
    - *env_scrappy_staging
  script:
    - python3 make.py configurator lint

migrate-scrappy:
  image: ${IMAGE_PIPELINE_RUNNER}
  stage: test
  before_script:
    - *env_scrappy_staging
  script:
    - python3 make.py scrappy migrate

migrate-configurator:
  image: ${IMAGE_PIPELINE_RUNNER}
  stage: test
  before_script:
    - *env_scrappy_staging
  script:
    - python3 make.py configurator migrate

test-viewer:
  image: ${IMAGE_PIPELINE_RUNNER}
  stage: test
  before_script:
    - *env_scrappy_staging
  script:
    - python3 make.py viewer test

lint-viewer:
  image: ${IMAGE_PIPELINE_RUNNER}
  stage: test
  before_script:
    - *env_scrappy_staging
  script:
    - python3 make.py viewer lint
