version: '3.8'
services:
  discorder_base:
    &discorder_base
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: dev
        SERVICE: discorder
      target: final
    ports:
      - "8030:8000"
    logging:
      driver: "json-file"
      options:
        max-buffer-size: "4m"
        mode: "non-blocking"
    environment:
      DISCORDER_DISCORD_TOKEN: "${DISCORDER_DISCORD_TOKEN:-example}"
    command: sh -c "exit"
  discorder_app:
    <<: *discorder_base
    command: python3 -m discorder