x-definitions:

  logging: &logging
    driver: "json-file"
    options:
      max-buffer-size: "4m"
      mode: "non-blocking"

  build: &build
    context: .
    dockerfile: Dockerfile
    args:
      ENVIRONMENT: dev
      SERVICE: viewer
    target: final-viewer

  environment: &environment
    VIEWER_CELERY_BROKER: "redis://viewer_redis:6379/0"
    VIEWER_CELERY_BACKEND: "redis://viewer_redis:6379/0"
    PYTEST_PLUGINS: celery.contrib.pytest
    SCRAPPY_API_URL: "http://scrappy_web:8000"
    CONFIGURATOR_API_URL: "http://configurator_web:8000"

  app: &app
    build: 
      <<: *build
    logging:
      <<: *logging
    environment:
      <<: *environment

version: '3.8'
services:
  viewer_redis:
    image: redis
    expose:
      - "6379"
    logging:
      <<: *logging
  viewer_base:
    <<: *app
    command: sh -c "exit"
  viewer_beat:
    <<: *app
    command: celery -A viewer.core.celery beat
  viewer_worker:
    <<: *app
    command: celery -A viewer.core.celery worker
  viewer_flower:
    <<: *app
    command: celery -A viewer.core.celery flower
    ports:
      - "5565:5555"
