name: Pages
'on':
  push:
    branches:
    - master
  workflow_dispatch: {}
jobs:
  job:
    name: Pages
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
      contents: read
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Check out source repository
      uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: ensure pip
      run: python3 -m ensurepip
    - name: Install requirements.txt
      run: pip install -r requirements.txt -c constraints.txt
    - name: Build docs
      run: mkdocs build
    - name: Upload artifacts for deployment to Github Pages
      uses: actions/upload-pages-artifact@v3
      with:
        name: github-pages
        path: './site'
    - name: Deploy to pages
      uses: actions/deploy-pages@v4
      id: deployment
