name: Test
'on':
  push:
    branches:
    - master
  schedule:
  - cron: '0 10 1 * *'
  workflow_dispatch: {}
jobs:
  job:
    name: Test
    runs-on: ubuntu-22.04
    steps:
    - name: Check out source repository
      uses: actions/checkout@v3
    - name: Install Go
      uses: darklab8/infra/.github/actions/install-go@master
    - name: Install Taskfile
      uses: darklab8/infra/.github/actions/install-taskfile@master
    - name: test
      run: task test
